---
environment: "${SPRING_PROFILES_ACTIVE:local}"

server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: "TwitchCommandControler-${environment}"
  main:
    banner-mode: "off"

management:
  server.port: ${MANAGEMENT_PORT:8081}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    prometheus:
      enabled: true

# Azure service bus properties
azure:
  service:
    bus:
      connection: Endpoint=sb://twitchmessages.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=E/4f207CQvnAIQMoeHrfoqXLYg/QbcedYGOHVOKzSgw=
      subscription: twitchmessages.servicebus.windows.net
      queue: test-1
      responseQueue: current-scene


message: "Hello from ${environment} environment and the current time is"
